export interface themeType {
  id: number;
  name: string;
  type: themeEnum;
  primaryColor: string;
  secondaryColor: string;
  textColor: string;
  bgImg: string;
}

export enum themeEnum {
  LIGHT = "light",
  DARK = "dark",
}

export const themes: themeType[] = [
  {
    id: 1,
    name: "Metallic Toad",
    type: themeEnum.LIGHT,
    primaryColor: "#abbaab",
    secondaryColor: "#ff5252",
    textColor: "#020508",
    bgImg: "linear-gradient(to bottom, #abbaab, #ffffff)",
  },
  {
    id: 2,
    name: "Deep Space",
    type: themeEnum.DARK,
    primaryColor: "#434343",
    secondaryColor: "#ffdb58",
    textColor: "#ffffff",
    bgImg: "linear-gradient(to top, #000000, #434343)",
  },
  {
    id: 3,
    name: "Ultra Voilet",
    type: themeEnum.DARK,
    primaryColor: "#654ea3",
    secondaryColor: "#ffb000",
    textColor: "#ffffff",
    bgImg: "linear-gradient(to right, #654ea3, #eaafc8)",
  },
  {
    id: 4,
    name: "Royal",
    type: themeEnum.DARK,
    primaryColor: "#141e30",
    secondaryColor: "#ff6f61",
    textColor: "#ffffff",
    bgImg: "linear-gradient(to top, #141e30, #243b55)",
  },
  {
    id: 5,
    name: "Fiery Bloom",
    type: themeEnum.DARK,
    primaryColor: "#c21010",
    secondaryColor: "#cfe8a9",
    textColor: "#fffde3",
    bgImg: "linear-gradient(to right, #c21010, #e64848)",
  },
  {
    id: 6,
    name: "Sage Meadow",
    type: themeEnum.DARK,
    primaryColor: "#627254",
    secondaryColor: "#fefded",
    textColor: "#eeeeee",
    bgImg: "linear-gradient(to right, #627254, #76885b)",
  },
  {
    id: 7,
    name: "Blue Raspberry",
    type: themeEnum.DARK,
    primaryColor: "#0083b0",
    secondaryColor: "#ffcc29",
    textColor: "#ffffff",
    bgImg: "linear-gradient(to top, #00b4db, #0083b0)",
  },
  {
    id: 8,
    name: "Piggy Pink",
    type: themeEnum.LIGHT,
    primaryColor: "#ffdde1",
    secondaryColor: "#1f3c18",
    textColor: "#303030",
    bgImg: "linear-gradient(to top, #ee9ca7, #ffdde1)",
  },
  {
    id: 9,
    name: "Twilight Spectrum",
    type: themeEnum.DARK,
    primaryColor: "#363062",
    secondaryColor: "#f99417",
    textColor: "#f5f5f5",
    bgImg: "linear-gradient(to right, #363062, #4d4c7d)",
  },
  {
    id: 10,
    name: "Pastel Paradise",
    type: themeEnum.LIGHT,
    primaryColor: "#fffadd",
    secondaryColor: "#8ecddd",
    textColor: "#22668d",
    bgImg: "#fffadd",
  },
  {
    id: 11,
    name: "Aqua Breeze",
    type: themeEnum.LIGHT,
    primaryColor: "#b3c8cf",
    secondaryColor: "#086065",
    textColor: "#162023",
    bgImg: "linear-gradient(to top, #bed7dc, #b3c8cf)",
  },
  {
    id: 12,
    name: "Delicate",
    type: themeEnum.LIGHT,
    primaryColor: "#e9e4f0",
    secondaryColor: "#3f3d56",
    textColor: "#333333",
    bgImg: "linear-gradient(to top, #d3cce3, #e9e4f0)",
  },
  {
    id: 13,
    name: "Dull",
    type: themeEnum.LIGHT,
    primaryColor: "#e2e2e2",
    secondaryColor: "#48515a",
    textColor: "#303030",
    bgImg: "linear-gradient(to top, #c9d6ff, #e2e2e2)",
  },
  {
    id: 14,
    name: "Modern Slate",
    type: themeEnum.LIGHT,
    primaryColor: "#dddddd",
    secondaryColor: "#f05454",
    textColor: "#222831",
    bgImg: "#dddddd",
  },
  {
    id: 15,
    name: "Sunlit Ocean",
    type: themeEnum.LIGHT,
    primaryColor: "#ffcc70",
    secondaryColor: "#22668d",
    textColor: "#303030",
    bgImg: "#fffadd",
  },
  {
    id: 16,
    name: "Bourbon",
    type: themeEnum.DARK,
    primaryColor: "#ec6f66",
    secondaryColor: "#3a1c71",
    textColor: "#fff",
    bgImg: "linear-gradient(to right, #ec6f66, #f3a183)",
  },
  {
    id: 17,
    name: "Mauve",
    type: themeEnum.DARK,
    primaryColor: "#734b6d",
    secondaryColor: "#b2cf5a",
    textColor: "#ffffff",
    bgImg: "linear-gradient(to top, #42275a, #734b6d)",
  },
  {
    id: 18,
    name: "Pale Wood",
    type: themeEnum.LIGHT,
    primaryColor: "#d6ae7b",
    secondaryColor: "#3b5249",
    textColor: "#030303",
    bgImg: "linear-gradient(to top, #eacda3, #d6ae7b)",
  },
  {
    id: 19,
    name: "Verdant Serenity",
    type: themeEnum.LIGHT,
    primaryColor: "#d2de32",
    secondaryColor: "#016a70",
    textColor: "#232323",
    bgImg: "linear-gradient(to top, #a2c579, #d2de32)",
  },
  {
    id: 20,
    name: "Ash",
    type: themeEnum.DARK,
    primaryColor: "#3f4c6b",
    secondaryColor: "#ff6f61",
    textColor: "#ffffff",
    bgImg: "linear-gradient(to top, #606c88, #3f4c6b)",
  },
  {
    id: 21,
    name: "Pastel Blush",
    type: themeEnum.LIGHT,
    primaryColor: "#ffc7c7",
    secondaryColor: "#8785a2",
    textColor: "#2f2f2f",
    bgImg: "linear-gradient(to top, #ffe2e2, #ffc7c7)",
  },
  {
    id: 22,
    name: "Nightfall Noir",
    type: themeEnum.DARK,
    primaryColor: "#161a30",
    secondaryColor: "#b6bbc4",
    textColor: "#f0ece5",
    bgImg: "linear-gradient(to bottom, #161a30, #31304d)",
  },
  {
    id: 23,
    name: "Twilight Horizon",
    type: themeEnum.DARK,
    primaryColor: "#141e30",
    secondaryColor: "#ff6f61",
    textColor: "#CFCFCF",
    bgImg: "linear-gradient(to right, #141e30, #243b55)",
  },
  {
    id: 24,
    name: "Limade Cooler",
    type: themeEnum.LIGHT,
    primaryColor: "#A1FFCE",
    secondaryColor: "#7851a9",
    textColor: "#363636",
    bgImg: "linear-gradient(to right, #A1FFCE, #FAFFD1)",
  },
  {
    id: 25,
    name: "Tranquil Tidepool",
    type: themeEnum.DARK,
    primaryColor: "#dcf2f1",
    secondaryColor: "#7fc7d9",
    textColor: "#0f1035",
    bgImg: "#dcf2f1",
  },
  {
    id: 26,
    name: "Fused Passion",
    type: themeEnum.DARK,
    primaryColor: "#800080",
    secondaryColor: "#ffd700",
    textColor: "#ffffff",
    bgImg: "linear-gradient(to right, #800080, #FFC0CB)",
  },
  {
    id: 27,
    name: "Roseanna",
    type: themeEnum.LIGHT,
    primaryColor: "#FFAFBD",
    secondaryColor: "#008080",
    textColor: "#171717",
    bgImg: "linear-gradient(to right, #FFAFBD, #FFC3A0)",
  },
  {
    id: 28,
    name: "Golden Horizon",
    type: themeEnum.DARK,
    primaryColor: "#0c356a",
    secondaryColor: "#ffc436",
    textColor: "#fff0ce",
    bgImg: "linear-gradient(to right, #0c356a, #0174be)",
  },
  {
    id: 29,
    name: "Mystic Midnight",
    type: themeEnum.DARK,
    primaryColor: "#4c4c6d",
    secondaryColor: "#1b9c85",
    textColor: "#e8f6ef",
    bgImg: "#4c4c6d",
  },
  {
    id: 30,
    name: "Violet Dreamscape",
    type: themeEnum.DARK,
    primaryColor: "#86469c",
    secondaryColor: "#f9faf9",
    textColor: "#101201",
    bgImg: "linear-gradient(to right, #bc7fcd, #86469c)",
  },
];
