export interface themeType {
  id: number;
  name: string;
  type: string;
  primaryColor: string;
  secondaryColor: string;
  bgImg: string;
}

export const themes = [
  {
    id: 1,
    name: "Metallic Toad",
    type: "light",
    primaryColor: "#abbaab",
    secondaryColor: "#ff5252",
    bgImg: "linear-gradient(to bottom, #abbaab, #ffffff)",
  },
  {
    id: 2,
    name: "Deep Space",
    type: "dark",
    primaryColor: "#434343",
    secondaryColor: "#ffdb58",
    bgImg: "linear-gradient(to top, #000000, #434343)",
  },
  {
    id: 3,
    name: "Ultra Voilet",
    type: "dark",
    primaryColor: "#654ea3",
    secondaryColor: "#ffb000",
    bgImg: "linear-gradient(to right, #654ea3, #eaafc8)",
  },
  {
    id: 4,
    name: "Royal",
    type: "dark",
    primaryColor: "#141e30",
    secondaryColor: "#ff6f61",
    bgImg: " linear-gradient(to top, #141e30, #243b55)",
  },
  {
    id: 5,
    name: "Yoda",
    type: "dark",
    primaryColor: "#493240",
    secondaryColor: "#45a0a3",
    bgImg: "linear-gradient(to top, #ff0099, #493240)",
  },
  {
    id: 6,
    name: "Cinnamint Flavour",
    type: "light",
    primaryColor: "#4ac29a",
    secondaryColor: "#fff",
    bgImg: "linear-gradient(to right, #4ac29a, #Bdfff3",
  },
  {
    id: 7,
    name: "Blue Raspberry",
    type: "light",
    primaryColor: "#0083b0",
    secondaryColor: "#ffcc29",
    bgImg: " linear-gradient(to top, #00b4db, #0083b0)",
  },
  {
    id: 8,
    name: "Piggy Pink",
    type: "light",
    primaryColor: "#ffdde1",
    secondaryColor: "#1f3c18",
    bgImg: "linear-gradient(to top, #ee9ca7, #ffdde1)",
  },
  {
    id: 9,
    name: "Margo",
    type: "light",
    primaryColor: "#ffefba",
    secondaryColor: "#001f3f",
    bgImg: " linear-gradient(to right, #ffefba, #ffffff)",
  },
  {
    id: 10,
    name: "Shifty",
    type: "dark",
    primaryColor: "#636363",
    secondaryColor: "#ffdb58",
    bgImg: "linear-gradient(to right, #636363, #a2ab58)",
  },
  {
    id: 11,
    name: "eXpresso",
    type: "dark",
    primaryColor: "#3c1053",
    secondaryColor: "#ffb000",
    bgImg: " linear-gradient(to top, #ad5389, #3c1053)",
  },
  {
    id: 12,
    name: "Delicate",
    type: "light",
    primaryColor: "#e9e4f0",
    secondaryColor: "#3f3d56",
    bgImg: "linear-gradient(to top, #d3cce3, #e9e4f0)",
  },
  {
    id: 13,
    name: "Dull",
    type: "light",
    primaryColor: "#e2e2e2",
    secondaryColor: "#48515a",
    bgImg: "linear-gradient(to top, #c9d6ff, #e2e2e2)",
  },
  {
    id: 14,
    name: "Broken Hearts",
    type: "light",
    primaryColor: "#fffcdc",
    secondaryColor: "#53131e",
    bgImg: "linear-gradient(to top, #d9a7c7, #fffcdc)",
  },
  {
    id: 15,
    name: "Sunkist",
    type: "light",
    primaryColor: "#f2c94c",
    secondaryColor: "#f2c94c",
    bgImg: " linear-gradient(to top, #f2994a, #f2c94c)",
  },
  {
    id: 16,
    name: "Bourbon",
    type: "light",
    primaryColor: "#ec6f66",
    secondaryColor: "#3a1c71",
    bgImg: "linear-gradient(to right, #ec6f66, #f3a183)",
  },
  {
    id: 17,
    name: "Mauve",
    type: "dark",
    primaryColor: "#734b6d",
    secondaryColor: "#b2cf5a",
    bgImg: "linear-gradient(to top, #42275a, #734b6d)",
  },
  {
    id: 18,
    name: "Pale Wood",
    type: "light",
    primaryColor: "#d6ae7b",
    secondaryColor: "#3b5249",
    bgImg: " linear-gradient(to top, #eacda3, #d6ae7b)",
  },
  {
    id: 19,
    name: "Little Leaf",
    type: "light",
    primaryColor: "#8dc26f",
    secondaryColor: "#6b2737",
    bgImg: "linear-gradient(to top, #76b852, #8dc26f)",
  },
  {
    id: 20,
    name: "Ash",
    type: "dark",
    primaryColor: "#3f4c6b",
    secondaryColor: "#ff6f61",
    bgImg: "linear-gradient(to top, #606c88, #3f4c6b)",
  },
  {
    id: 21,
    name: "Midnight City",
    type: "dark",
    primaryColor: "#414345",
    secondaryColor: "#a1869e",
    bgImg: " linear-gradient(to top, #232526, #414345)",
  },
  {
    id: 22,
    name: "Mirage",
    type: "dark",
    primaryColor: "#16222a",
    secondaryColor: "#ff6f61",
    bgImg: "linear-gradient(to bottom, #16222a, #3a6073)",
  },
  {
    id: 23,
    name: "Twilight Horizon",
    type: "dark",
    primaryColor: "#141e30",
    secondaryColor: "#ff6f61",
    bgImg: "linear-gradient(to right, #141e30, #243b55)",
  },
  {
    id: 24,
    name: "Limade Cooler",
    type: "light",
    primaryColor: "#A1FFCE",
    secondaryColor: "#7851a9",
    bgImg: "linear-gradient(to right, #A1FFCE, #FAFFD1",
  },
  {
    id: 25,
    name: "Chitty Chitty Bang Bang",
    type: "dark",
    primaryColor: "#007991",
    secondaryColor: "#ffeb3b",
    bgImg: "linear-gradient(to right, #007991, #78FFD6",
  },
  {
    id: 26,
    name: "Fused Passion",
    type: "dark",
    primaryColor: "#800080",
    secondaryColor: "#ffd700",
    bgImg: "linear-gradient(to right, #800080, #FFC0CB",
  },
  {
    id: 27,
    name: "Roseanna",
    type: "light",
    primaryColor: "#FFAFBD",
    secondaryColor: "#008080",
    bgImg: "linear-gradient(to right, #FFAFBD, #FFC3A0",
  },
  {
    id: 28,
    name: "Decent",
    type: "dark",
    primaryColor: "#4ca1af",
    secondaryColor: "#af6f61",
    bgImg: "linear-gradient(to right, #4ca1af, #c4e0e5",
  },
];

// All gradients are collected from https://uigradients.com/
