import type { Metadata } from "next";
import { Poppins, Nunito_Sans } from "next/font/google";
import "./globals.css";
import connectDB, { isMongoConnected } from "@/db/db";
import AuthProvider from "../components/AuthProvider";
import { themes } from "@/theme";
import PreferencesProvider from "@/components/PreferenceProvider";
import { cookies } from "next/headers";
import setThemeInCookie from "@/actions/actions";

export const poppins_init = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const nunito_Sans_init = Nunito_Sans({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Otaku-io",
  description: "Generated by create next app",
};

export const getUserTheme = () => {
  let themeCookie = cookies().get("themeId");
  let themeId = 23;
  if (!themeCookie) {
    setThemeInCookie(23);
  } else {
    themeId = Number(themeCookie.value);
  }
  const userTheme = themes.find((theme) => theme.id === themeId) || themes[22];
  return userTheme;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = getUserTheme();
  if (!isMongoConnected) await connectDB();

  return (
    <html lang="en">
      <AuthProvider>
        <PreferencesProvider>
          <body
            id="App"
            className={`${poppins_init.variable} ${nunito_Sans_init.variable} font-poppins w-full relative`}>
            <div
              className="fixed -z-20 w-screen h-screen bg-cover"
              style={{
                backgroundColor: theme.primaryColor,
                background: theme.bgImg,
              }}
            />
            {children}
          </body>
        </PreferencesProvider>
      </AuthProvider>
    </html>
  );
}
