import type { Metadata } from "next";
import { Poppins, Nunito_Sans } from "next/font/google";
import "./globals.css";
import connectDB, { isMongoConnected } from "@/db/db";
import AuthProvider from "../components/AuthProvider";
import TopNavbar from "@/components/TopNavbar";
import { themes } from "@/theme";
import PreferencesProvider from "@/components/PreferenceProvider";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const nunito_Sans = Nunito_Sans({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Otaku-io",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = themes[1];
  if (!isMongoConnected) await connectDB();

  return (
    <html lang="en">
      <AuthProvider>
        <PreferencesProvider>
          <body
            id="App"
            className={`${poppins.variable} ${nunito_Sans.variable}w-full relative`}>
            <div
              className="fixed -z-20 w-screen h-screen bg-cover"
              style={{
                backgroundColor: theme.primaryColor,
                background: theme.bgImg,
              }}></div>
            {children}
          </body>
        </PreferencesProvider>
      </AuthProvider>
    </html>
  );
}
